name: Deploy Static Website to GitHub Pages

on:
  push:
    branches:
      - main  # Exécuter l'action sur push vers main

permissions:
  contents: read
  pages: write
  id-token: write  # Permet d'écrire sur GitHub Pages

jobs:
  build:
    name: Build Static Website
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4  # Récupérer le code du dépôt

      - name: Préparer les fichiers
        run: |
          mkdir public
          cp -r * public
          echo "Fichiers préparés dans le dossier public"

      - name: Upload des fichiers pour GitHub Pages
        uses: actions/upload-pages-artifact@v2  # ✅ Upload des fichiers pour Pages
        with:
          path: public

  deploy:
    name: Deploy to GitHub Pages
    needs: build  # 🚀 Dépend du job de build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Déployer sur GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2  # ✅ Dernière version recommandée
