name: Deploy Static Website to GitHub Pages

on:
  push:
    branches:
      - main  # Déclencher l'action lorsqu'un commit est poussé sur `main`

permissions:
  contents: read
  pages: write
  id-token: write  # Autorise l'accès à GitHub Pages

jobs:
  deploy:
    runs-on: ubuntu-latest  # Utilise une machine Linux

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4  # Récupère le code du dépôt

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v4  # Configure GitHub Pages

      - name: Préparer les fichiers pour le déploiement
        run: |
          mkdir public
          cp -r * public
          echo "Les fichiers sont prêts pour le déploiement"

      - name: Upload des fichiers (nouvelle version)
        uses: actions/upload-pages-artifact@v2  # ✅ Version correcte
        with:
          path: public  # 📌 On envoie uniquement le dossier public

      - name: Déployer sur GitHub Pages
        uses: actions/deploy-pages@v2  # ✅ Version mise à jour
